[package]
name = "expanda"
version = "0.4.5"
edition = "2024"

description = "`expand` macro to replace and simplify single-use `macro_rules!`"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Quelfth/expanda"

[dependencies]
expanda-macros = {version = "0.4.5", path = "../expanda-macros"}
